---
title: "Using Functions"
author: "Matthew Yancheff"
date: "May 24, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rcv)
```

```{r}
mayorballotimage <- old_ballot_tidy(rawimage = "http://www.acgov.org/rov/rcv/results/230/BerkeleyMayor/ballot_image.txt", 
                                     masterkey = "http://www.acgov.org/rov/rcv/results/230/BerkeleyMayor/master_lookup.txt")

nicemayorimage <- mayorballotimage %>% 
  filter(vote_rank != 4) %>%
  spread(key = vote_rank, value = candidate)

mayorelectionresults <- old_rcv_tally(rcvimage = mayorballotimage, rcvcontest = "Mayor - Berkeley (RCV)")


districtballotimage <- old_ballot_tidy("http://www.sfelections.org/results/20161108/data/20161206/20161206_ballotimage.txt", 
                                        "http://www.sfelections.org/results/20161108/data/20161206/20161206_masterlookup.txt")


district7results <- old_rcv_tally(districtballotimage, "Board of Supervisors, District 7")

old_rcv_plot(rcvresults = district7results)
old_rcv_plot(mayorelectionresults)

```

```{r}
for (j in unique(districtballotimage$contest)) {
  assign(paste0("Election:", j, "Results"), 
         old_rcv_tally(rcvimage = districtballotimage, rcvcontest = j))
}
```
